### ISSUE TITLE
Textures use very similar patterns like Minecraft

### ISSUE THREAD

**Issue by flo** [Drullkus/Chisel-Textures#7]
I noticed that some patterns of the textures are very similar to the one from minecraft.

I suggest we remove any texture with an identical pattern like minecraft that is not just trival from the repository. Otherwise there is the danger that we get sued.

The texture stone_bricks-cracked looks almost identical like the cracked stone brick from minecraft. It has the exact same cracks. Any other blocks that came from same source should be double checked.

The textures *_pillar-top look also very similar like a block in minecraft.

*_prism blocks share not only the name but also the pattern with "Prismarine bricks". While it is not 100% identical it looks very similar.

Also endstone, glowstone and redstone is something invented by minecraft so I think  those blocks should be removed too.

**Comment by Drullkus** [comment]
Everything in this Repo is 100% kosher.

**Comment by Cervator** [comment]
Oh hey @Drullkus I was just about to ping you to ask if any textures from there are at all based on just modifying a base MC texture - but I guess they're all custom from scratch then?

It may still be a good idea to at least rename some stuff. This module was just a rush effort by me, I'd rather we redo it more properly at some point in the future (better naming, maybe better upstream connection for updates, maybe better automated textures where doable, etc)

**Comment by Drullkus** [comment]
Let me clarify: These are images that I hand-made myself. No byte or even bits of data from the Mojang textures were used by me.

Moving onto resemblance, these patterns are exactly hand-crafted by me to look as faithful as possible to the original pattern design, but they were not copy pasted from the Minecraft textures. The point of this is to offer same patterns of a pattern exclusive to one block to another block. 

So you can have Prismarine Bricks' Prism patterns as Bricks, grout and all.

On the point of Glowstone / End stone / Redstone have to be stylistically similar. They are those materials! It has to be the same Vanilla style. I leave any other stylistic interpretations to resource packs.

**Comment by Cervator** [comment]
Oh, wait - also, wrong repo, @flo did you mean to raise the issue in https://github.com/Terasology/ChiselBlocks ? I didn't even notice this was @Drullkus' root repo at first, thought it was our fork.

Thanks for the comment @Drullkus - yeah makes perfect sense with the naming as it is in *this* repo :-)

**Comment by Drullkus** [comment]
@cervator they're all from scratch, for Minecraft Mod Chisel. That's what this repo is for. :P

**Comment by Drullkus** [comment]
OH. I see what's happening now. @flo You're coming from the Terasology community? 

Yes, it looks like Minecraft because it IS for a Minecraft Mod. :P

**Comment by flo** [comment]
@Cervator since this is root repository, terasology one has no issue tracker.

@Drullkus First of: thanks then for putting so much effort in it to redo all. 

However please think about it how others might think of it when a block has even the same cracks. If someone notices that he gets the wrong impression. For that reason I would strongly suggest you change the cracks or remove the block. Also if terasology becomes a success I am sure that minecraft would use something like that to sue.

**Comment by Cervator** [comment]
Ah right, the issue tracker doesn't auto-enable for forks, you have to do so manually. Done!

https://github.com/Terasology/ChiselBlocks/issues

I think the similarity to MC is just something we have to worry about in our fork. Plenty of nice cool unique textures, we can cut out a few sets and still have plenty of fun blocks to play with :-)

**Comment by flo** [comment]
ah okay, sorry then for the trouble, I thought you made it for terasology :)
